### ISSUE TITLE
Create Relaton gem

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/relaton#1]
Create the Relaton gem.

```ruby
x = Relaton.fetch("ISO19011")
=> Relaton::Error "No such fetcher"

require 'relaton-iso'
x = Relaton.fetch("ISO19011")
=> <# Relaton::Iso @docidentifier: "ISO 19011:2011" ... >

x.to_xml
=> <bib-item ...>
```

Types of bibliographic items, such as isobib, gbbib, rfcbib (called bibliographic engine) should "register" themselves to Relaton (e.g. which regular expression will this bibliographic engine handle).

This gem should also handle caching (document local, and machine global):

* Relaton machine global database (e.g., "~/.relaton/db.json")
* Relaton local database (e.g., "~/documents/iso-rice/relaton-bib/")
* allow saving entries to global / local database (`Relaton::Database.add(:global, Relaton.fetch("ISO19011"))`)
* allow loading entries (`Relaton::Database.load(:local, doc_identifier: "ISO19011")`)
* allow listing entries (`Relaton::Database.list.map(&:to_s)`)
* allow exporting entries (`Relaton::Database.load(:local, doc_identifier: "ISO19011").to_xml / to_bibtex / to_rfcxml` ...)

**Comment by opoudjis** [comment]
I am concerned about folding the GB standards codes into this sat without a universal  disambiguating prefix. Outside the context of Chinese standards, a prefix like NY is insufficiently specific. I propose to use "GB Standard" as a prefix for all Chinese standards, which is filled in by the gem for asciidoctor-gb

**Comment by ronaldtse** [comment]
You're right.

But do you mean citing with a key like `<<GB Standard GM/T 0009-2012>>` or `<<GBGMT00092012>>` (`Relaton.fetch("GBGMT00092012")`, or ...?

Let's define proper patterns for every standard type, and we should document this so others know how to cite for auto-fetch?

**Comment by opoudjis** [comment]
The cache key and the fetch key should be the human readable key; I don't see a reason for it not to be. So `GB Standard GM/T 0009-2012`.

We will need to do likewise for IETF; I've already seen that ISO prefixes IETF to RFC, and RFC itself doesn't bother.

I don't believe ISO and IEC need further prefixing.

**Comment by opoudjis** [comment]
The relaton gem right now implements just Isobib calls, and just takes XML from the cache and the website. Initialising it specifies a filename for a global and a local cache. It works with asciidoctor-iso.

But the spec above is much, much bigger, and I want @andrew2net involved, rather than doing it all myself.

**Comment by opoudjis** [comment]
Done:

* registering isobib to register in relaton
* registering required prefix of isobib references to relaton
* iterating through required prefixes in relaton to match code
* initialising local database
* initialising global database
* loading entire database (JSON object, XML content)
* saving entire database (JSON object, XML content)

To do:
* returning Relaton class (isobibitem) instead of XML string as representation of entry
* unmarshalling entries from database: https://github.com/riboseinc/iso-bib-item/issues/1
* marshalling entries to database
* loading individual entry from database
* saving individual entry to database
* listing entries
* extending all of the above to the other two gems, gbbib, rfcbib
* implementing to_rfcxml (which I'm just going to do by storing the original RFC XML)

**Comment by andrew2net** [comment]
@opoudjis do you intend to split the tasks between us?

**Comment by andrew2net** [comment]
@opoudjis I'm starting to work on **returning Relaton class (isobibitem) instead of XML string as representation of entry**

**Comment by opoudjis** [comment]
Thank you. The story is going to be:

* Read XML from cache, when you do read it, into isobibitem class. That's what the Unmarshal task enabled
* Return isobibitem class for all calls to fetch. (The recipient then has to serialise it to xml; I'll do that in asciidoctor-iso)
* Explicitly marshal isobibitem class back to XML for caching
* Load individual entry, and save individual entry (which can mean converting the JSON object into a key/value database)

**Comment by andrew2net** [comment]
@opoudjis saying **Load individual entry** do you mean we should load entries one by one and check if a key match to the code, to avoid loading entire DB into memory?

**Comment by opoudjis** [comment]
Yes, return IsoBibliographicItem from isobib.

**Comment by opoudjis** [comment]
I think Ronald invisions ass not loading all entries from the database at once, but only one by one as needed. That means that, for relaton, a reference will be loaded from the database only if we are checking whether it already exists there, for a get. You will need to load all entries for the list operation.

**Comment by opoudjis** [comment]
You may choose to do this using a key value database, instead of a json object.

**Comment by opoudjis** [comment]
@andrew2net, it looks like you have implemented all the required tasks for isobib. I am going to test, then integrate with asciidoctor-iso, then close this ticket. Integrating gbbib and rfcbib with relaton (and with particular gems) are new tickets. Thank you!

**Comment by opoudjis** [comment]
The testing, I'm afraid, was not as extensive as I would have preferred, and I had to fix a fair few things to get it working with Asciidoctor-ISO and with existing ISO references; but that's all done now.
